In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
import numpy as np
arr = np.array(my_list)
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)
np.arange(0,10)
np.arange(0,11,3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 3, 6, 9])

array([ 0.,  0.,  0.])

In [14]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [17]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
np.linspace(0,5,5)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [22]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.rand(5)

array([ 0.96398038,  0.42370055,  0.15833963,  0.43727803,  0.82312444])

In [24]:
np.random.rand(5,5)

array([[ 0.69793595,  0.32781569,  0.07551642,  0.38563742,  0.75667375],
       [ 0.08928764,  0.46385659,  0.52793004,  0.97144911,  0.59741805],
       [ 0.27639919,  0.35997245,  0.89952489,  0.83127682,  0.11203519],
       [ 0.99901035,  0.54941561,  0.67257407,  0.70039001,  0.05786726],
       [ 0.35243874,  0.09325788,  0.78390389,  0.90477207,  0.43013118]])

In [25]:
np.random.randn(2)

array([ 0.64366895,  1.09540659])

In [26]:
np.random.randn(4,4)

array([[-0.4147602 , -0.4559719 ,  0.42622944, -0.15874863],
       [-0.93816476, -1.47416486,  0.80860429, -0.49147962],
       [ 0.18105461,  0.64097144, -1.8115158 ,  0.00425915],
       [ 0.94964298, -0.26355322,  0.2399227 ,  0.95382721]])

In [27]:
np.random.randint(1,100)

32

In [28]:
np.random.randint(1,100,10)

array([ 9, 38, 37, 45, 48, 80, 33, 46,  4, 30])

In [30]:
arr = np.arange(25)

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([47,  9, 24, 21, 41, 33, 27,  4, 12,  1])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr

array([47,  9, 24, 21, 41, 33, 27,  4, 12,  1])

In [35]:
ranarr.max()

47

In [36]:
ranarr.min()

1

In [37]:
ranarr

array([47,  9, 24, 21, 41, 33, 27,  4, 12,  1])

In [38]:
ranarr.argmax()

0

In [39]:
ranarr.argmin()

9

In [40]:
arr.shape

(25,)

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.shape

(5, 5)

In [47]:
arr.dtype

dtype('int32')

In [48]:
from numpy.random import randint

In [49]:
randint(2,10)

7

In [50]:
# NumPy Indexing and Selection 

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[8]

8

In [54]:
arr[1:5]

array([1, 2, 3, 4])

In [55]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [56]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [57]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[0:5] = 100 

In [59]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [64]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_arr[:] = 99

In [66]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr.copy()

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:] = 100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
arr_2d[0][0]

5

In [81]:
arr_2d[0,0]

5

In [95]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [94]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [96]:
# conditional selection

In [97]:
arr = np.arange(1,11)

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
bool_arr = arr > 5

In [101]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [102]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [103]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [104]:
arr[arr<3]

array([1, 2])

In [107]:
arr_2d = np.arange(50).reshape(5,10)

In [108]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [109]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [110]:
#Numpy Operations

In [111]:
arr = np.arange(0,11)

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [114]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [118]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [119]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [121]:
arr / arr

C:\Users\joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [122]:
1/ arr

C:\Users\joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [123]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [124]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [125]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [126]:
np.max(arr)

10

In [127]:
arr.max()

10

In [128]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [129]:
np.log(arr)

C:\Users\joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [5]:
# import the required module  
import matplotlib.pyplot as plt 
# plot a histogram  
df['Observation Value'].hist(bins=10) 
  
# shows presence of a lot of outliers/extreme values 
df.boxplot(column='Observation Value', by = 'Time period') 
  
# plotting points as a scatter plot 
x = df["Observation Value"] 
y = df["Time period"] 
plt.scatter(x, y, label= "stars", color= "m",  
            marker= "*", s=30) 
# x-axis label 
plt.xlabel('Observation Value') 
# frequency label 
plt.ylabel('Time period') 
# function to show the plot 
plt.show() 

NameError: name 'df' is not defined

In [9]:
import pandas as pd
# assigning two series to s1 and s2 
s1 = pd.Series([1,2]) 
s2 = pd.Series(["Ashish", "Sid"]) 
# framing series objects into data 
df = pd.DataFrame([s1,s2]) 
# show the data frame 
df 
  
# data framing in another way 
# taking index and column values 
dframe = pd.DataFrame([[1,2],["Ashish", "Sid"]], 
        index=["r1", "r2"], 
        columns=["c1", "c2"]) 
dframe 
  
# framing in another way  
# dict-like container 
dframe = pd.DataFrame({ 
        "c1": [1, "Ashish"], 
        "c2": [2, "Sid"]}) 
dframe 

c1   c2
0       1    2
1  Ashish  Sid

In [10]:
# Import the pandas library, renamed as pd 
import pandas as pd 
  
# Read IND_data.csv into a DataFrame, assigned to df 
df = pd.read_csv("IND_data.csv") 
  
# Prints the first 5 rows of a DataFrame as default 
df.head() 
  
# Prints no. of rows and columns of a DataFrame 
df.shape 

FileNotFoundError: File b'IND_data.csv' does not exist

In [11]:
# prints first 5 rows and every column which replicates df.head() 
df.iloc[0:5,:] 
# prints entire rows and columns 
df.iloc[:,:] 
# prints from 5th rows and first 5 columns 
df.iloc[5:,:5]

Empty DataFrame
Columns: [0, 1]
Index: []

In [12]:
# import the required module  
import matplotlib.pyplot as plt 
# plot a histogram  
df['Observation Value'].hist(bins=10) 
  
# shows presence of a lot of outliers/extreme values 
df.boxplot(column='Observation Value', by = 'Time period') 
  
# plotting points as a scatter plot 
x = df["Observation Value"] 
y = df["Time period"] 
plt.scatter(x, y, label= "stars", color= "m",  
            marker= "*", s=30) 
# x-axis label 
plt.xlabel('Observation Value') 
# frequency label 
plt.ylabel('Time period') 
# function to show the plot 
plt.show() 

KeyError: 'Observation Value'